name: flutter_mvvm_structure
description: Flutter MVVM Code Structure
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  shared_preferences:
  flutter_switch:
  sensors:
  pin_code_fields:
  google_sign_in:
  firebase_auth:
  flutter_facebook_login:
  http:
  sign_in_with_apple:
  provider:
  cloud_firestore:
  firebase_storage:
  firebase_crashlytics:
  firebase_core:
  firebase_messaging:
  image_picker:
  package_info:
  flutter_html:
  firebase_dynamic_links:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/

  fonts:
    - family: Brandon
      fonts:
        - asset: assets/fonts/brandon/BrandonGrotesque-Regular.otf
          weight: 400
        - asset: assets/fonts/brandon/BrandonGrotesque-Medium.otf
          weight: 500
        - asset: assets/fonts/brandon/BrandonGrotesque-Bold.otf
          weight: 700
        - asset: assets/fonts/brandon/BrandonGrotesque-Black.otf
          weight: 900
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
    - family: Playlist
      fonts:
        - asset: assets/fonts/playlist/Playlist-Script.otf
          weight: 400
    - family: Lora
      fonts:
        - asset: assets/fonts/lora/Lora-Medium.ttf
          weight: 400
        - asset: assets/fonts/lora/Lora-Regular_Bold.ttf
          weight: 500
        - asset: assets/fonts/lora/Lora-Bold.ttf
          weight: 700